# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createkey.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Createkey(object):
    def setupUi(self, Createkey):
        Createkey.setObjectName("Createkey")
        Createkey.resize(439, 430)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Createkey)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Createkey)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineComment = QtWidgets.QLineEdit(self.frame)
        self.lineComment.setText("")
        self.lineComment.setObjectName("lineComment")
        self.gridLayout_2.addWidget(self.lineComment, 5, 0, 1, 2)
        self.lineEmail = QtWidgets.QLineEdit(self.frame)
        self.lineEmail.setText("")
        self.lineEmail.setObjectName("lineEmail")
        self.gridLayout_2.addWidget(self.lineEmail, 3, 0, 1, 2)
        self.lineName = QtWidgets.QLineEdit(self.frame)
        self.lineName.setText("")
        self.lineName.setObjectName("lineName")
        self.gridLayout_2.addWidget(self.lineName, 1, 0, 1, 2)
        self.checkExpire = QtWidgets.QCheckBox(self.frame)
        self.checkExpire.setChecked(True)
        self.checkExpire.setObjectName("checkExpire")
        self.gridLayout_2.addWidget(self.checkExpire, 7, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2013, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setDate(QtCore.QDate(2013, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 7, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Createkey)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.comboLength = QtWidgets.QComboBox(self.frame_2)
        self.comboLength.setObjectName("comboLength")
        self.comboLength.addItem("")
        self.comboLength.addItem("")
        self.comboLength.addItem("")
        self.gridLayout.addWidget(self.comboLength, 1, 1, 1, 1)
        self.comboAlgo = QtWidgets.QComboBox(self.frame_2)
        self.comboAlgo.setObjectName("comboAlgo")
        self.comboAlgo.addItem("")
        self.comboAlgo.addItem("")
        self.gridLayout.addWidget(self.comboAlgo, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.comboAlgo2 = QtWidgets.QComboBox(self.frame_2)
        self.comboAlgo2.setObjectName("comboAlgo2")
        self.comboAlgo2.addItem("")
        self.comboAlgo2.addItem("")
        self.gridLayout.addWidget(self.comboAlgo2, 2, 2, 1, 1)
        self.comboLength2 = QtWidgets.QComboBox(self.frame_2)
        self.comboLength2.setObjectName("comboLength2")
        self.comboLength2.addItem("")
        self.comboLength2.addItem("")
        self.comboLength2.addItem("")
        self.gridLayout.addWidget(self.comboLength2, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.linePassphrase = QtWidgets.QLineEdit(self.frame_2)
        self.linePassphrase.setText("")
        self.linePassphrase.setObjectName("linePassphrase")
        self.gridLayout.addWidget(self.linePassphrase, 3, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(Createkey)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushCancel = QtWidgets.QPushButton(self.frame_3)
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout.addWidget(self.pushCancel)
        self.pushGenerate = QtWidgets.QPushButton(self.frame_3)
        self.pushGenerate.setObjectName("pushGenerate")
        self.horizontalLayout.addWidget(self.pushGenerate)
        self.verticalLayout_2.addWidget(self.frame_3)

        self.retranslateUi(Createkey)
        QtCore.QMetaObject.connectSlotsByName(Createkey)

    def retranslateUi(self, Createkey):
        _translate = QtCore.QCoreApplication.translate
        Createkey.setWindowTitle(_translate("Createkey", "Create key-pair"))
        self.label_9.setText(_translate("Createkey", "Expire :"))
        self.label_3.setText(_translate("Createkey", "Comment (optionel) :"))
        self.label_2.setText(_translate("Createkey", "Your email :"))
        self.label.setText(_translate("Createkey", "Your Name (minimum of 5 chars :) :"))
        self.checkExpire.setText(_translate("Createkey", "No expiration"))
        self.comboLength.setItemText(0, _translate("Createkey", "1024"))
        self.comboLength.setItemText(1, _translate("Createkey", "2048"))
        self.comboLength.setItemText(2, _translate("Createkey", "4096"))
        self.comboAlgo.setItemText(0, _translate("Createkey", "RSA"))
        self.comboAlgo.setItemText(1, _translate("Createkey", "DSA"))
        self.label_6.setText(_translate("Createkey", "Passphrase :"))
        self.label_4.setText(_translate("Createkey", "Primary key :"))
        self.label_5.setText(_translate("Createkey", "Key type"))
        self.comboAlgo2.setItemText(0, _translate("Createkey", "RSA"))
        self.comboAlgo2.setItemText(1, _translate("Createkey", "ELG-E"))
        self.comboLength2.setItemText(0, _translate("Createkey", "1024"))
        self.comboLength2.setItemText(1, _translate("Createkey", "2048"))
        self.comboLength2.setItemText(2, _translate("Createkey", "4096"))
        self.label_7.setText(_translate("Createkey", "Subkey :"))
        self.label_8.setText(_translate("Createkey", "Key size"))
        self.pushCancel.setText(_translate("Createkey", "Cancel"))
        self.pushGenerate.setText(_translate("Createkey", "Generate"))

