# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keymanager.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Fenkeymanager(object):
    def setupUi(self, Fenkeymanager):
        Fenkeymanager.setObjectName("Fenkeymanager")
        Fenkeymanager.resize(553, 393)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Fenkeymanager)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Fenkeymanager)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkPrivates = QtWidgets.QCheckBox(self.frame)
        self.checkPrivates.setObjectName("checkPrivates")
        self.horizontalLayout.addWidget(self.checkPrivates)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame)
        self.listWidget = QtWidgets.QListWidget(Fenkeymanager)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.groupBox = QtWidgets.QGroupBox(Fenkeymanager)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_nom = QtWidgets.QLabel(self.groupBox)
        self.label_nom.setText("")
        self.label_nom.setObjectName("label_nom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_nom)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_empreinte = QtWidgets.QLabel(self.groupBox)
        self.label_empreinte.setText("")
        self.label_empreinte.setObjectName("label_empreinte")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_empreinte)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_identifiant = QtWidgets.QLabel(self.groupBox)
        self.label_identifiant.setText("")
        self.label_identifiant.setObjectName("label_identifiant")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_identifiant)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_creation = QtWidgets.QLabel(self.groupBox)
        self.label_creation.setText("")
        self.label_creation.setObjectName("label_creation")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_creation)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_expiration = QtWidgets.QLabel(self.groupBox)
        self.label_expiration.setText("")
        self.label_expiration.setObjectName("label_expiration")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_expiration)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_algorithme = QtWidgets.QLabel(self.groupBox)
        self.label_algorithme.setText("")
        self.label_algorithme.setObjectName("label_algorithme")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_algorithme)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_taille = QtWidgets.QLabel(self.groupBox)
        self.label_taille.setText("")
        self.label_taille.setObjectName("label_taille")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_taille)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_confiance = QtWidgets.QLabel(self.groupBox)
        self.label_confiance.setText("")
        self.label_confiance.setObjectName("label_confiance")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_confiance)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame_2 = QtWidgets.QFrame(Fenkeymanager)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushCancel = QtWidgets.QPushButton(self.frame_2)
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout_2.addWidget(self.pushCancel)
        self.pushModify = QtWidgets.QPushButton(self.frame_2)
        self.pushModify.setObjectName("pushModify")
        self.horizontalLayout_2.addWidget(self.pushModify)
        self.pushCreate = QtWidgets.QPushButton(self.frame_2)
        self.pushCreate.setObjectName("pushCreate")
        self.horizontalLayout_2.addWidget(self.pushCreate)
        self.pushDelete = QtWidgets.QPushButton(self.frame_2)
        self.pushDelete.setObjectName("pushDelete")
        self.horizontalLayout_2.addWidget(self.pushDelete)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit.setEnabled(True)
        self.dateEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dateEdit.setReadOnly(True)
        self.dateEdit.setDisplayFormat("dd/MM/yy")
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_2)

        self.retranslateUi(Fenkeymanager)
        QtCore.QMetaObject.connectSlotsByName(Fenkeymanager)

    def retranslateUi(self, Fenkeymanager):
        _translate = QtCore.QCoreApplication.translate
        Fenkeymanager.setWindowTitle(_translate("Fenkeymanager", "Key Manager"))
        self.checkPrivates.setText(_translate("Fenkeymanager", "Show only privates keys"))
        self.listWidget.setSortingEnabled(False)
        self.groupBox.setTitle(_translate("Fenkeymanager", "Key Property"))
        self.label.setText(_translate("Fenkeymanager", "Name :"))
        self.label_2.setText(_translate("Fenkeymanager", "Fingerprint :"))
        self.label_6.setText(_translate("Fenkeymanager", "Id:"))
        self.label_3.setText(_translate("Fenkeymanager", "Creation date :"))
        self.label_4.setText(_translate("Fenkeymanager", "Expiration date :"))
        self.label_7.setText(_translate("Fenkeymanager", "Algorithm :"))
        self.label_8.setText(_translate("Fenkeymanager", "Key size :"))
        self.label_9.setText(_translate("Fenkeymanager", "Trust :"))
        self.pushCancel.setText(_translate("Fenkeymanager", "Close"))
        self.pushModify.setText(_translate("Fenkeymanager", "Edit key (not imp.)"))
        self.pushCreate.setText(_translate("Fenkeymanager", "Créate key"))
        self.pushDelete.setText(_translate("Fenkeymanager", "Delete key"))

